output_dir: /kaggle/working/output/movielens

dataset:
  class: MovieLensDataset
  path: /kaggle/working/datasets/recommendation
  version: "100k"

task:
  class: tasks.LinkPrediction
  criterion: bce
  metric: [auroc, ap]
  model:
    class: model.GRSNN
    input_dim: 32
    hidden_dim: 32
    num_relation: 1
    num_mlp_layer: 2
    time_steps: 5
    delay_bound: 4
    Vth: 2.0
    tau: 4.0
    temporal_decay_ratio: 0.95
    num_beam: 10
    path_topk: 10
    symmetric: false
    self_connection: false
    boundary_query: true
    concat_hidden: false
    layer_norm: false
    relation_weight: false
    not_delay: false
    dependent: true
    aggregate_func: sum
    linear_scale: 1.0
    m_regularization: 0.0
    surrogate_function: sigmoid
    tau_c: null
  num_negative: 1
  strict_negative: yes

optimizer:
  class: optim.Adam
  lr: 0.001
  amsgrad: false
  betas: [0.9, 0.999]
  eps: 0.00000001
  weight_decay: 0.0

engine:
  gpus: {{ gpus }}
  batch_size: 8
  amp_training: false

train:
  num_epoch: 20

gpus: [0]
logger: logging
