output_dir: ./experiments/

dataset:
  class: MovieLensDataset
  path: ./datasets/recommendation/
  version: 100k

task:
  class: LinkPrediction
  model:
    class: GRSNN
    input_dim: 32
    hidden_dim: 32
    dependent: yes
    remove_one_hop: no
    tau: 4.0
    Vth: 2.0
    delay_bound: 4
    self_connection: False
    time_steps: 10
    temporal_decay_ratio: 0.95
  criterion: bce
  num_negative: 5
  strict_negative: yes

optimizer:
  class: Adam
  lr: 0.001

engine:
  gpus: [0]
  batch_size: 128

train:
  num_epoch: 20

metric: mrr
