output_dir: ./experiments/

dataset:
  class: WN18RR
  path: ./datasets/knowledge_graphs/

task:
  class: KnowledgeGraphCompletionSNN
  model:
    class: GRSNN
    input_dim: 32
    hidden_dim: 32
    dependent: yes
    tau: 4.
    Vth: 2.
    delay_bound: 4
    self_connection: yes
    time_steps: 10
    temporal_decay_ratio: 0.95
    boundary_query: yes
    relation_weight: yes
    layer_norm: yes
  criterion: bce
  num_negative: 256
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: no

optimizer:
  class: Adam
  lr: 2.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 8
  gradient_interval: 4

train:
  num_epoch: 20

metric: mrr
